### PR TITLE
removes colorama to fix issue #24

### PR DESCRIPTION
**Pull request by dorzey**

### CODE REVIEW

**Comment by dorzey** [comment]
Might have been a bit premature. I think it might still be being pulled in as a transitive dependency

**Comment by dorzey** [comment]
@bloomonkey @samwedge this works on my machine with dbt 0.18.1; but can you double-check?

Could we do something with a GitHub Action to verify dbt compatibility?

**Comment by bloomonkey** [comment]
I expect it's pulled in as a transitive by `click` - we can probably pin it to something comaptible.
Yes, I think we can probably check compatibility with one or more dbt releases, I'll take a look.

**Comment by bloomonkey** [comment]
@dorzey CI Checks now added for compatibility across Python and dbt versions

**Pull request merged**
